stages:
  - build
  - validate
  - security
  - deploy

maven-build:
  image: maven:3.9.4-eclipse-temurin-21
  stage: build
  script: "mvn clean package -DskipTests"
  artifacts:
    paths:
      - target/gitlab-ci-demo.jar


dependency-check:
  image: owasp/dependency-check:latest
  stage: security
  variables:
    PROJECT_NAME: "springboot-app"
  script:
    - /usr/share/dependency-check/bin/dependency-check.sh \
        --project "$PROJECT_NAME" \
        --scan . \
        --format "HTML" \
        --out dependency-check-report
  artifacts:
    paths:
      - dependency-check-report
    when: always
    expire_in: 1 week
  only:
    - merge_requests
    - main
    - develop
  allow_failure: true
